name: Server CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Server CI Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout DownFlux repository
      uses: actions/checkout@v1

    - name: Mount Bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install Bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Run CI tests
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test -c opt --features race //... --nocache_test_results --runs_per_test=100
